/**
 * Fixture content for /specimen — the dev-only design system page.
 *
 * This is not the site's copy. Phase 6 writes the home page and phase 7 the
 * secondary routes; what is here exists so every component can be rendered in
 * every state and diffed against the reference.
 *
 * It is still written in the house voice, and deliberately so. Lorem ipsum has
 * uniform word lengths and no capitals, so it hides exactly the faults a
 * specimen page is built to expose: a line-height that is too tight for
 * ascenders, a column that is too wide to read, a mono label that wraps at one
 * viewport and not the other.
 *
 * The artwork is generated by scripts/stand-ins.mjs and imported from
 * app/assets/, which means the bundler only emits it if something references
 * it — and the only thing that does is this file, which no production route
 * reaches.
 */
import plate1 from '~/assets/plates/plate-01.webp'
import plate2 from '~/assets/plates/plate-02.webp'
import plate3 from '~/assets/plates/plate-03.webp'
import plate4 from '~/assets/plates/plate-04.webp'
import mark1 from '~/assets/plates/mark-01.png'
import mark2 from '~/assets/plates/mark-02.png'
import dial from '~/assets/plates/dial-01.png'

const PLATE = { w: 640, h: 854 }

/* -------------------------------------------------------------------------- */
/* the ledger                                                                 */
/* -------------------------------------------------------------------------- */

export const ledgerHeads = ['Lot', 'Season', 'Grade', 'Net kg', 'Crocin'] as const

const estate = { src: mark1, describe: 'Estate mark' }
const bench = { src: mark2, describe: 'Assay bench mark' }

export const ledgerRows = [
  { marks: [estate, bench], name: 'CRC-0417 · Sierpe', cells: ['2025', 'Coupé', '4.20'], value: '248' },
  { marks: [estate, bench], name: 'CRC-0418 · Sierpe', cells: ['2025', 'Coupé', '6.00'], value: '244' },
  { marks: [estate, bench], name: 'CRC-0421 · Valdehierro', cells: ['2025', 'Mancha', '12.50'], value: '211' },
  { marks: [estate, bench], name: 'CRC-0426 · Romeral', cells: ['2024', 'Mancha', '9.80'], value: '203' },
  { marks: [estate, bench], name: 'CRC-0430 · Valdehierro', cells: ['2024', 'Río', '15.00'], value: '187' },
] as const

/* -------------------------------------------------------------------------- */
/* the accordion                                                              */
/* -------------------------------------------------------------------------- */

export const questions = [
  {
    question: 'What travels with a sealed lot?',
    body:
      'One seal covers four documents: the estate note, the assay sheet, the ' +
      'moisture reading taken at intake, and the bonded warehousing record. ' +
      'Break the seal and the lot is graded again before it moves.',
  },
  {
    question: 'How is a grade decided?',
    body:
      'By hand, then by instrument. Threads are sorted for style length and ' +
      'for the ratio of red to yellow, and a sample goes to the bench for ' +
      'colour strength, crocin and safranal. The bench figure is the one ' +
      'printed on the certificate. The sorter has the last word on style.',
  },
  {
    question: 'Do you sell below a kilogram?',
    body:
      'No. The house sells lots. The smallest lot on the ledger is four ' +
      'kilograms net and it is sold whole.',
  },
  {
    question: 'How long does a lot hold?',
    body:
      'Sealed, unlit, at a steady twelve degrees, a lot holds its colour ' +
      'strength for thirty months. The intake date is struck on every tin, so ' +
      'the buyer is never estimating.',
  },
] as const

/* -------------------------------------------------------------------------- */
/* the tab panel                                                              */
/* -------------------------------------------------------------------------- */

export const tabs = [
  {
    label: 'Cultivation',
    body:
      'Corms are lifted and re-set on a four-year cycle across nineteen ' +
      'bonded estates. Every field is walked before dawn through the three ' +
      'weeks of flowering; the flower is picked closed and stripped the same ' +
      'morning.',
  },
  {
    label: 'Grading',
    body:
      'Stripping, curing and sorting all happen under one roof at Consuegra. ' +
      'Threads are cured over low heat to a fixed moisture, then sorted by ' +
      'style length before anything reaches the assay bench.',
  },
] as const

/* -------------------------------------------------------------------------- */
/* the carousel                                                               */
/* -------------------------------------------------------------------------- */

export const cards = [
  {
    tag: 'Lot 04',
    date: '12 Nov 2025',
    title: 'The season closes early',
    plate: { src: plate1, describe: 'Cured threads on a sorting tray', ...PLATE },
    to: '/',
  },
  {
    tag: 'Lot 09',
    date: '03 Nov 2025',
    title: 'Two benches, one figure',
    plate: { src: plate2, describe: 'The assay bench at Consuegra', ...PLATE },
    to: '/',
  },
  {
    tag: 'Lot 17',
    date: '28 Oct 2025',
    title: 'Valdehierro is re-set',
    plate: { src: plate3, describe: 'A field walked before dawn', ...PLATE },
    to: '/',
  },
  {
    tag: 'Lot 22',
    date: '14 Oct 2025',
    title: 'On weighing a flower',
    plate: { src: plate4, describe: 'A brass scale in the weigh room', ...PLATE },
    to: '/',
  },
] as const

/* -------------------------------------------------------------------------- */
/* the tiles                                                                  */
/* -------------------------------------------------------------------------- */

export const tiles = [
  { label: 'Estates', plate: { src: plate3, describe: '', ...PLATE }, to: '/' },
  { label: 'Assay', plate: { src: plate2, describe: '', ...PLATE }, to: '/' },
  { label: 'Ledger', plate: { src: plate4, describe: '', ...PLATE }, to: '/' },
  { label: 'Journal', plate: { src: plate1, describe: '', ...PLATE }, to: '/' },
] as const

/* -------------------------------------------------------------------------- */
/* the marquee                                                                */
/* -------------------------------------------------------------------------- */

/** Our trade bodies. The reference's partner marks are never reproduced. */
export const bodies = [
  'Consejo Regulador',
  'Lonja de Albacete',
  'Cámara de Toledo',
  'Instituto del Azafrán',
  'Aduana de Castilla',
] as const

/* -------------------------------------------------------------------------- */
/* the footer disclosure                                                      */
/* -------------------------------------------------------------------------- */

export const footerRows = [
  {
    question: 'House',
    body:
      'Founded 1904 at Consuegra, Toledo. Nineteen bonded estates across ' +
      'Castile-La Mancha, one grading floor, one assay bench.',
  },
  {
    question: 'Trade',
    body:
      'Lots are offered on the open ledger and settled against the bench ' +
      'figure. Bonded warehousing is charged by the month and by the tin.',
  },
] as const

/* -------------------------------------------------------------------------- */
/* long-form, for the .txt block                                              */
/* -------------------------------------------------------------------------- */

export const prose = {
  head: 'On weight and measure',
  lead:
    'A lot is weighed three times: at intake, after curing, and again under ' +
    'the seal. The third figure is the one that binds.',
  list: [
    'Intake weight, taken wet, within four hours of picking.',
    'Cured weight, taken at a fixed moisture, never estimated from the first.',
    'Sealed weight, witnessed, struck on the tin and on the certificate.',
  ],
  tail:
    'Where the three disagree by more than half a percent the lot is held and ' +
    'the bench is asked to look again. It is a slow rule and it has been the ' +
    'house rule since 1904.',
} as const

/* -------------------------------------------------------------------------- */
/* the pinned scene — phase 3, task 3.3                                       */
/* -------------------------------------------------------------------------- */

/**
 * Four steps of a season. The real four arrive with phase 6; these exist so
 * the pin, the discrete step boundaries, the reverse crossing and the
 * reduced-motion stack can all be checked against something with real copy in
 * it — a scene tested with four identical grey cards is a scene where nobody
 * notices the caption never changed.
 */
export const reel = [
  {
    tag: 'One · June',
    title: 'The corms go down',
    body:
      'Valdehierro is turned, limed and left to settle. Corms are set at fifteen ' +
      'centimetres on a metre bed. Nothing is watered. The block will not be walked ' +
      'again until the first flowers show.',
    plate: { src: plate3, describe: 'Turned ground at Valdehierro, early summer', ...PLATE },
  },
  {
    tag: 'Two · 28 October',
    title: 'The rose is lifted',
    body:
      'Picking starts before light and stops when the flower opens. A picker takes ' +
      'the whole rose, not the thread. Four hours a day, eleven days, and the block ' +
      'is finished for the year.',
    plate: { src: plate1, describe: 'A field walked before dawn at the end of October', ...PLATE },
  },
  {
    tag: 'Three · the same day',
    title: 'Three threads to a flower',
    body:
      'Stripping is done sitting, indoors, within the day. Three stigmas to a ' +
      'flower and one hundred and fifty thousand flowers to the kilogram. The ' +
      'count is the price and everyone at the table knows it.',
    plate: { src: plate2, describe: 'The stripping bench, threads on a paper tray', ...PLATE },
  },
  {
    tag: 'Four · November',
    title: 'Dried, weighed, sealed',
    body:
      'Curing over low heat takes the weight down by four fifths. What comes off ' +
      'the tray is assayed for crocin, entered against the lot, and goes into ' +
      'bonded warehousing under seal.',
    plate: { src: plate4, describe: 'A brass scale and a sealed tin in the weigh room', ...PLATE },
  },
] as const

/* -------------------------------------------------------------------------- */
/* the GL scenes — phase 3, tasks 3.4 to 3.7                                  */
/* -------------------------------------------------------------------------- */

/**
 * Stand-ins, and honest about it.
 *
 * `face` is scripts/stand-ins.mjs's coin blank: the ring band is drawn as
 * TICKS at the radius and weight the lettering will carry, so the specimen
 * settles the only question task 3.5 asks of it — is a band at that radius
 * legible at 375px — without pretending to be the artwork. Phase 5 bakes the
 * real face.
 *
 * `still` is a plate, not a render. Phase 5 generates one static frame per
 * scene from the scene itself; until then this is enough to exercise the
 * fallback PATH, which is the part that rots silently.
 */
export const scenes = {
  face: dial,
  still: { src: plate2, ...PLATE },
} as const
