/**
 * The cap-height ledger — rule 4, measured rather than eyeballed.
 *
 * Every generator that draws a term prints the cap height that term lands at
 * on a 375px viewport, exits non-zero under the floor, and records the number
 * here. scripts/register.mjs reads the file back and closes R10 with it, so
 * _private/KEY.md carries a measurement that came out of the run that made the
 * artwork rather than one somebody typed.
 *
 * WHY A SEPARATE FILE AND NOT `cap375` IN placements.json
 *
 * placements.json is judgement — where the six live, and the only place that
 * decision is recorded. A generator that writes into it can silently overwrite
 * a decision with a measurement. Keeping the two apart means the register stays
 * hand-authored and the measurements stay machine-authored, and the audit is
 * the only thing that joins them.
 *
 * THE ARITHMETIC BEHIND "375px"
 *
 * main.css sets `--global-font-size: clamp(5px, (100vw / var(--size)) * 10,
 * var(--clamp))` with `--size: 375` below the one breakpoint. At a 375px
 * viewport that computes to exactly 10px, so `1rem = 10 design px` and a
 * design pixel IS a CSS pixel there. Every number in this file is therefore
 * both at once, which is the only reason a generator can measure a page it
 * cannot see.
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'

/** Rule 4's floor, and the viewport it is measured at. Phase 4 §2 sets both. */
export const FLOOR = 7
export const VIEWPORT = 375

/**
 * Merges measurements into _private/reach.json.
 *
 * Merged rather than rewritten because two generators own different terms and
 * either may be run alone — `node scripts/plates.mjs stamp-01` must not delete
 * the outline generator's entry. Keys are sorted on the way out so a partial
 * run and a full run produce the same file.
 */
export function record(root, entries) {
  const vault = join(root, '_private')
  if (!existsSync(vault)) return null
  mkdirSync(vault, { recursive: true })

  const file = join(vault, 'reach.json')
  const held = existsSync(file) ? JSON.parse(readFileSync(file, 'utf8')) : {}

  const book = { ...(held.measured ?? {}) }
  for (const entry of entries) book[entry.id] = entry

  const out = {
    _note:
      'GENERATED by the phase 5 generators through scripts/lib/reach.mjs. ' +
      'Organiser-only, git-ignored. scripts/register.mjs reads it to close R10. ' +
      'Do not edit by hand — re-run the generator that owns the entry.',
    floorPx: FLOOR,
    viewportPx: VIEWPORT,
    measured: Object.fromEntries(Object.keys(book).sort().map((k) => [k, book[k]])),
  }

  writeFileSync(file, JSON.stringify(out, null, 2) + '\n', 'utf8')
  return file
}

/**
 * Formats one measurement for a generator's report, and says whether it passed.
 *
 * The generator decides what to do about a failure — plates.mjs has several
 * terms and wants to report all of them before it exits, rather than stopping
 * at the first.
 */
export function grade(capPx) {
  const ok = capPx >= FLOOR
  const n = capPx.toFixed(1).padStart(5)
  return { ok, line: `${n}px cap at ${VIEWPORT}px  ${ok ? 'ok' : `UNDER THE ${FLOOR}px FLOOR`}` }
}
