import { cn } from '@/lib/cn'

/* ==========================================================================
   Two text utilities. Their jobs are completely different and must never be
   confused for one another.

     <Split/>        cuts a line into per-character spans so motion can
                     stagger them. Decoration. Nothing more.
     <OutlineText/>  draws a line from committed path geometry, so the
                     document contains shapes where the words would be.

   Read the note above each one before using it.
   ========================================================================== */

type SplitProps = {
  /** The line of copy to render. */
  text: string
  /** Element to render as. Defaults to a span. */
  as?: 'span' | 'h1' | 'h2' | 'h3' | 'p'
  className?: string
  /** Class applied to each generated character, for per-unit animation. */
  unitClassName?: string
}

/**
 * Splits a line into one span per character so GSAP can stagger them.
 *
 * ┌──────────────────────────────────────────────────────────────────────┐
 * │ PURELY DECORATIVE. This is an ANIMATION tool. It is NOT a defence    │
 * │ against find-in-page and offers no protection of any kind.           │
 * │                                                                      │
 * │ Chrome normalises text ACROSS inline element boundaries before it    │
 * │ matches. Three spans holding R, A and G are matched exactly as if    │
 * │ they were one word. GSAP SplitText behaves identically. Anyone who   │
 * │ assumes otherwise and routes a concealed term through here has       │
 * │ published that term in plain text.                                   │
 * │                                                                      │
 * │ Use <OutlineText/> below when a line must not be matchable.          │
 * └──────────────────────────────────────────────────────────────────────┘
 *
 * Accessibility: the wrapper carries the whole line as its accessible name and
 * every character span is removed from the tree, so assistive technology reads
 * one string rather than spelling it out.
 *
 * Words stay intact. Characters are grouped into an inline-block per word, so
 * a line wraps between words like ordinary copy and never mid-word.
 */
export function Split({ text, as = 'span', className, unitClassName }: SplitProps) {
  const Tag = as
  const words = text.split(' ')

  return (
    <Tag className={cn('inline-block', className)} aria-label={text}>
      {words.map((word, w) => (
        <span key={`${word}-${w}`} aria-hidden="true" className="inline-block whitespace-pre">
          {[...word].map((glyph, g) => (
            <span key={`${glyph}-${g}`} className={cn('inline-block', unitClassName)}>
              {glyph}
            </span>
          ))}
          {/* A real space, preserved by the wrapper's whitespace-pre. Using
              &nbsp; here would put U+00A0 into anything the reader copies. */}
          {w === words.length - 1 ? null : (
            <span className={cn('inline-block', unitClassName)}> </span>
          )}
        </span>
      ))}
    </Tag>
  )
}

type OutlineTextProps = {
  /** Path geometry, one entry per glyph. Generated by scripts/outline.mjs. */
  paths: string[]
  /** The viewBox the geometry was authored against. */
  viewBox: string
  /** What the line says. Becomes the accessible name for the whole drawing. */
  label: string
  /**
   * Drop this drawing out of the accessibility tree entirely.
   *
   * For the one case where a headline is set as two stacked drawings that are
   * a single sentence: the wrapper carries `role="img"` and the whole line as
   * its accessible name, and the halves are muted so a screen reader announces
   * the headline once rather than twice in pieces. `label` is still required,
   * and is still the right value — it documents what the geometry says for
   * whoever edits this next.
   */
  mute?: boolean
  className?: string
}

/**
 * Renders a line of display type from committed path geometry.
 *
 * The markup is an <svg role="img"> containing nothing but <path> elements.
 * That is the whole point and it is not negotiable:
 *
 *   - There is no text node, so find-in-page has nothing to walk.
 *   - There is no <text> element either. Inline SVG <text> IS matched by
 *     Chrome, and using it here would quietly undo the entire technique. If a
 *     future edit needs a character this file cannot draw, regenerate the
 *     geometry — do not reach for <text>.
 *
 * ACCESSIBILITY TRADE-OFF (recorded in CLAUDE.md).
 * A headline drawn as geometry cannot be selected, copied, translated by the
 * browser, or reflowed at large text settings. The mitigation is the
 * aria-label: screen readers announce the line normally, and the drawing
 * scales with its container rather than being a fixed-size raster. This is the
 * accepted cost of an intentionally non-selectable headline, and it is why the
 * technique is used on display type only — never on running copy.
 *
 * Fill is `currentColor`, so the line inherits its scene's --fore exactly like
 * every other headline on the site and can never read as a special case.
 */
export function OutlineText({ paths, viewBox, label, mute, className }: OutlineTextProps) {
  return (
    <svg
      role={mute ? undefined : 'img'}
      aria-label={mute ? undefined : label}
      aria-hidden={mute || undefined}
      viewBox={viewBox}
      preserveAspectRatio="xMidYMid meet"
      focusable="false"
      fill="currentColor"
      className={cn('h-auto w-full', className)}
    >
      {paths.map((d, i) => (
        <path key={i} d={d} />
      ))}
    </svg>
  )
}
